/**
 * Created by ling xue  on 15-10-23.
 */

/**
 * RABBIT QUEUE TYPE
 * */

var RABBIT_QUEUE_ERROR = "error" ;
var RABBIT_QUEUE_NORMAL = "mp" ;

var MESSAGE_TYPE_SMS = "1" ;
var MESSAGE_TYPE_EMAIL = "2";

var MESSAGE_SUB_TYPE_SIGNIN = "1" ;
var MESSAGE_SUB_TYPE_PASSWORD = "2";
var MESSAGE_SUB_TYPE_ACTIVE = "3";

var RABBIT_EXCHANGE = "mp";
var RABBIT_TOPIC_NOTIFICATION = "notification";
var RABBIT_TOPIC_ORDER = "order";

var MESSAGE_SMS_PASSWORD = {
    type : MESSAGE_TYPE_SMS ,
    subType : MESSAGE_SUB_TYPE_PASSWORD,
    phone : 'phone',
    code : 'captchaKey'
};

var MESSAGE_SMS_SIGNIN = {
    type : MESSAGE_TYPE_SMS ,
    subType : MESSAGE_SUB_TYPE_SIGNIN,
    phone : 'phone',
    code : 'captchaKey'
};

var MESSAGE_EMAIL_USER_ACTIVE = {
    type : MESSAGE_TYPE_EMAIL ,
    subType : MESSAGE_SUB_TYPE_ACTIVE,
    email : 'email'
};


module.exports ={
    RABBIT_QUEUE_ERROR : RABBIT_QUEUE_ERROR,
    RABBIT_QUEUE_NORMAL : RABBIT_QUEUE_NORMAL ,
    MESSAGE_TYPE_SMS : MESSAGE_TYPE_SMS ,
    MESSAGE_SUB_TYPE_PASSWORD : MESSAGE_SUB_TYPE_PASSWORD ,
    MESSAGE_SUB_TYPE_SIGNIN : MESSAGE_SUB_TYPE_SIGNIN ,
    RABBIT_EXCHANGE : RABBIT_EXCHANGE ,
    RABBIT_TOPIC_NOTIFICATION : RABBIT_TOPIC_NOTIFICATION ,
    RABBIT_TOPIC_ORDER : RABBIT_TOPIC_ORDER ,
    MESSAGE_SMS_PASSWORD : MESSAGE_SMS_PASSWORD ,
    MESSAGE_SMS_SIGNIN : MESSAGE_SMS_SIGNIN ,
    MESSAGE_EMAIL_USER_ACTIVE : MESSAGE_EMAIL_USER_ACTIVE
}