var ERROR_PARAMS_EMPTY = "输入内容不能为空";
var ERROR_USER_NAME_ADDED = "此用户名已被注册";
var ERROR_DRIVER_REFER_USED = "邀请码已经被使用,请联系车队管理员";
var ERROR_TRUCKTEAM_ADDED = "该车队已经添加";
var ERROR_USER_VALIDATE = "用户名或密码错误";
var ERROR_TRUCK_ADDED = "该车辆已被登记";
var ERROR_DRIVER_ADDED = "该司机已被登记";
var ERROR_VERIFY_ADDED = "该用户已被认证";
var ERROR_VERIFY_YET = "尚未通过审核";
var ERROR_DEVICE_TOKEN_ADDED = "设备已存在";
var ERROR_BIZ_LIC_ADDED = "该企业已经认证过，请联系管理员{@@}给你添加子账号权限";
var ERROR_WECHAT_MISSED = "微信用户不存在";
var ERROR_BIZ_OCCUPIED = "该手机号已认证为其他企业下的员工，确认有异议，请联系客服，联系方式400-686-6000。";
var ERROR_DEPARTMENT_ADDED = "部门已经添加";
var ERROR_BOOKING_FAILED = "预约提箱失败";
var ERROR_CANCEL_BOOKING = "取消预约失败";
var ERROR_NO_CONTAINER = "没有可预约的箱源";
var ERROR_TYPE_INCORRECT = "只能添加与当前用户身份相符的子账号";
var ERROR_CORE_BIZ_ADDED = "该地区已经订阅";
var ERROR_REQUEST_TOO_FAST = "请求过于频繁";
var ERROR_LOGIN_EXPIRED = "登录信息过期，请重新登录";

module.exports = {
    ERROR_PARAMS_EMPTY: ERROR_PARAMS_EMPTY,
    ERROR_DRIVER_REFER_USED: ERROR_DRIVER_REFER_USED,
    ERROR_TRUCKTEAM_ADDED: ERROR_TRUCKTEAM_ADDED,
    ERROR_USER_VALIDATE: ERROR_USER_VALIDATE,
    ERROR_TRUCK_ADDED: ERROR_TRUCK_ADDED,
    ERROR_DRIVER_ADDED: ERROR_DRIVER_ADDED,
    ERROR_VERIFY_ADDED: ERROR_VERIFY_ADDED,
    ERROR_VERIFY_YET: ERROR_VERIFY_YET,
    ERROR_DEVICE_TOKEN_ADDED: ERROR_DEVICE_TOKEN_ADDED,
    ERROR_BIZ_LIC_ADDED: ERROR_BIZ_LIC_ADDED,
    ERROR_WECHAT_MISSED: ERROR_WECHAT_MISSED,
    ERROR_BIZ_OCCUPIED: ERROR_BIZ_OCCUPIED,
    ERROR_DEPARTMENT_ADDED: ERROR_DEPARTMENT_ADDED,
    ERROR_BOOKING_FAILED: ERROR_BOOKING_FAILED,
    ERROR_CANCEL_BOOKING: ERROR_CANCEL_BOOKING,
    ERROR_NO_CONTAINER: ERROR_NO_CONTAINER,
    ERROR_USER_NAME_ADDED: ERROR_USER_NAME_ADDED,
    ERROR_TYPE_INCORRECT: ERROR_TYPE_INCORRECT,
    ERROR_CORE_BIZ_ADDED: ERROR_CORE_BIZ_ADDED,
    ERROR_LOGIN_EXPIRED: ERROR_LOGIN_EXPIRED
};